/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package assignment.java.oop.panelsFM;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;
import java.awt.Color;
import java.awt.Component;
import javax.swing.table.DefaultTableCellRenderer;


public class ViewPRsPOs_Panel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPRsPOs_Panel
     */
    public ViewPRsPOs_Panel() {
        initComponents();
        loadPurchaseRequisitions();
        loadPurchaseOrders();
        applyStatusColorRenderer(tablePRs, 5); 
        applyStatusColorRenderer(tablePOs, 5); 

    }
    
     private void loadPurchaseRequisitions() {
        DefaultTableModel model = (DefaultTableModel) tablePRs.getModel();
        model.setRowCount(0); // Clear previous data
        String path = "C:\\Users\\user\\Documents\\NetBeansProjects\\JAVAOOP\\src\\assignment\\java\\oop\\FM data\\purchase_requisitions.txt";
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length >= 6) {
                    model.addRow(data);
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error loading PRs: " + e.getMessage());
        }
    }
     
     private void loadPurchaseOrders() {
        DefaultTableModel model = (DefaultTableModel) tablePOs.getModel();
        model.setRowCount(0); // Clear previous data
        String path = "src/assignment/java/oop/FM data/purchase_orders.txt";
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] data = line.split(",");
                if (data.length >= 7) {
                    model.addRow(data);
                }
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error loading POs: " + e.getMessage());
        }
    }
     
    private void applyStatusColorRenderer(JTable table, int statusColumnIndex) {
    table.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable tbl, Object value, boolean isSelected,
                                                       boolean hasFocus, int row, int column) {
            Component c = super.getTableCellRendererComponent(tbl, value, isSelected, hasFocus, row, column);

            // Check if row exists before accessing
            if (row < tbl.getRowCount()) {
                String status = tbl.getValueAt(row, statusColumnIndex).toString();

                if (!isSelected) {
                    if ("Approved".equalsIgnoreCase(status)) {
                        c.setBackground(new Color(200, 255, 200));
                    } else if ("Declined".equalsIgnoreCase(status)) {
                        c.setBackground(new Color(255, 200, 200)); 
                    } else if ("Received".equalsIgnoreCase(status)) {
                        c.setBackground(new Color(255, 255, 180));
                    } else if ("Paid".equalsIgnoreCase(status)) {
                        c.setBackground(new Color(180, 220, 255));
                    } else {
                        c.setBackground(Color.WHITE); 
                    }
                } else {
                    c.setBackground(tbl.getSelectionBackground());
                }
                c.setForeground(Color.BLACK);
            }

            return c;
        }
    });
}


     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePRs = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePOs = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("View Purchases Requisitions");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("View Purchase Orders");

        tablePRs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "PR ID", "Item", "Qty", "Price", "Requested By", "Date"
            }
        ));
        jScrollPane1.setViewportView(tablePRs);

        tablePOs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PO ID", "Supplier", "Item", "Qty", "Price", "Status", "Date"
            }
        ));
        jScrollPane2.setViewportView(tablePOs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablePOs;
    private javax.swing.JTable tablePRs;
    // End of variables declaration//GEN-END:variables
}
